# xAILab
# Chair of Explainable Machine Learning
# Otto-Friedrich University of Bamberg
#
# Parameter and hyperparameter configurations for the evaluation of the pretraining.

# Parameters
dataset: 'camelyon17'  # Which dataset to use.
data_path: '../data/camelyon17'  # Where the dataset is stored
input_path: '../checkpoints/pretrain'  # Where the trained model is stored.
output_path: '../output/pretrain'  # Parent directory to where the trained model shall be stored.
img_size: 224  # Height and width of the input
in_channel: 3  # Channel dimension of the input
num_mixes: 4  # Number of mixtures to sample from.
seed: 126423251  # Seed for random operations for reproducibility.
batch_size: 64  # Batch size for the evaluation. (64, 16)
device: 'cuda:0'  # Which device to run the computations on.
kwargs:
    patch_size: 16  # Size of image patches.
    embedding_dim: 768  # Latent space dimension of the encoder. (768, 1056)
    depth: 12 # Depth (Number of blocks) of the encoder and decoder. (12, 24)
    num_heads: 16  # Number of attention heads.
    mlp_ratio: 4.  # Ratio of the hidden dimension compared to the input dimension of the Multi-Layer-Perceptron (MLP) - layer.
    norm_layer: 'nn.LayerNorm'  # Normalization layer.